- name: install packages
  apt:
    name:
    - stow
    - git
    - tmux
    - ripgrep
    - curl
    - zsh
    - neofetch
    - htop
    - openssh-server
    - vim-gtk
    - ansible
    state: latest
